# Generated by Django 3.0.4 on 2020-05-07 13:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='report',
            field=models.ManyToManyField(blank=True, related_name='report', to=settings.AUTH_USER_MODEL),
        ),
    ]
